name    = XML-Builder
version = 0.906
author  = Aristotle Pagaltzis <pagaltzis@gmx.de>
license = Perl_5
copyright_holder = Aristotle Pagaltzis
copyright_year   = 2015

; authordep Dist::Zilla = 5.030
; https://github.com/rjbs/Dist-Zilla/issues/404

[MetaResources]
repository.type  = git
repository.url   = git://github.com/ap/XML-Builder.git
repository.web = https://github.com/ap/XML-Builder
bugtracker.web = https://github.com/ap/XML-Builder/issues

[@Filter]
-bundle=@Basic
-remove=Readme
[Readme::Brief]
[ReadmeAnyFromPod / PodInRoot]
[MetaJSON]
[PkgVersion]
[PodWeaver]
[CheckChangeLog]
[AutoPrereqs]
[CheckSelfDependency]
